name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scan on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full history for secret scanning
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        pip install bandit[toml] detect-secrets safety

    - name: Run Bandit Security Linter
      run: |
        mkdir -p reports
        bandit -r backend/ -f json -o reports/bandit-report.json --skip B101,B601 || true
        bandit -r backend/ --skip B101,B601 || true

    - name: Check for secrets
      run: |
        echo "Checking for potential secrets..."
        if detect-secrets scan --all-files --baseline .secrets.baseline --exclude-files node_modules/ --exclude-files __pycache__/; then
          echo "✅ No new secrets detected"
        else
          echo "⚠️  Potential secrets found - please review (informational)"
        fi

    - name: Check Python dependencies for vulnerabilities
      run: |
        if [ -f backend/requirements.txt ]; then
          echo "Checking Python dependencies for known vulnerabilities..."
          safety check -r backend/requirements.txt --ignore 70612 || true
        fi

    - name: Scan for hardcoded credentials (strict for literals)
      run: |
        echo "Scanning for hardcoded credentials..."
        MATCHES=$(grep -r -n -E "(password|passwd|pass|secret|token|api[_-]?key|access[_-]?key)\\s*[:=]\\s*['\"][^'\"]+['\"]" \
          --include="*.py" --include="*.js" --include="*.ts" --include="*.json" \
          --exclude-dir=node_modules --exclude-dir="__pycache__" --exclude="*.example" --exclude="*.spec.ts" --exclude="*.test.*" \
          . | grep -viE "(TEMP_FALLBACK|REPLACE_WITH|SET_YOUR|ENV\\(|process\\.env|os\\.environ|getenv|DEMO_PASSWORD|password_hash|generate_password_hash|bcrypt|hashlib)" || true)
        if [ -n "$MATCHES" ]; then
          echo "$MATCHES"
          echo "❌ Potential hardcoded credentials detected!" && exit 1
        else
          echo "✅ No hardcoded credentials detected"
        fi

    - name: Check for .env files
      run: |
        echo "Checking for committed .env files..."
        if find . -name ".env" -not -path "./node_modules/*" | grep -v ".env.example" | grep -q . ; then
          echo "❌ .env files found in repository!"
          find . -name ".env" -not -path "./node_modules/*" | grep -v ".env.example"
          exit 1
        else
          echo "✅ No .env files found"
        fi

    - name: Upload Bandit results to GitHub
      if: always() && hashFiles('reports/bandit-report.json') != ''
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/bandit-report.json
      continue-on-error: true

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'  # Don't fail on vulnerabilities, just report

    - name: Upload Trivy results to GitHub Security
      if: always() && hashFiles('trivy-results.sarif') != ''
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true